# Generated by Django 4.0.3 on 2022-04-13 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Airports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=200)),
                ('airport_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Flights',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin_city', models.CharField(max_length=200)),
                ('origin_airport', models.CharField(max_length=200)),
                ('dest_city', models.CharField(max_length=200)),
                ('dest_airport', models.CharField(max_length=200)),
                ('datetime', models.DateTimeField()),
                ('price', models.FloatField()),
                ('carrier', models.CharField(max_length=200)),
                ('flight_class', models.CharField(max_length=200)),
                ('plane_type', models.CharField(max_length=200)),
            ],
        ),
    ]
